### ISSUE TITLE
FastDFS客户端连接服务端问题

### ISSUE THREAD

**Issue by 920671233** [ixingjue/laravel-fastdfs#1]
有一点疑问，代码中没有涉及到**服务端ip和端口号**的设置，也没有**连接服务端**的操作，那么客户端是怎样去连接服务端的，给调度服务器和存储服务器发起请求的？

**Comment by ixingjue** [comment]
谢谢反馈 尽快处理并告知

**Comment by ixingjue** [comment]
@920671233 谢谢反馈 将会尽快反馈并修复

**Comment by no-serve-people** [comment]
@920671233 你好，必须先在服务器编译fastdfs的php_client扩展，才可正常使用该扩展包的php api
